apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{values.name}}-dep'
spec:
  template:
    labels:
      app: '{{values.app}}'
      spec:
        containers:
        - name: hello
          image: '{{values.image.repository}}:{{values.image.tag}}'